version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: 'test'
    restart: always
    volumes:
      - test-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: test

volumes:
  test-disk: